[tool.poetry]
name = "kod"
version = "0.1.0"
description = "Kod package management"
authors = ["Antal Buss <antal.buss@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
lupa = "^2.2"
invoke = "^2.2.0"

[tool.poetry.scripts]
ant = "kod.main:program.run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
