[project]
name = "kod"
version = "0.1.4.1"
description = "Kod package management"
authors = [{name="Antal Buss"}, {email="antal.buss@gmail.com"}]
readme = "README.md"
requires-python = ">= 3.14"
dependencies = [
  "lupa >= 2.6",
  "click >= 8.1.8",
  "chorut>=0.1.8",
]

[project.urls]
Repository = "https://github.com/kodos-prj/kodos"

[project.scripts]
kod = "kod.kod:cli"
nkod = "kod.nkod:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
  "pytest>=8.4.2",
]

[tool.ruff]
line-length = 120
