-- Example Custom Program for KodOS
-- File: ~/.kod/plugins/programs/redis.lua
--
-- This example demonstrates how to create a custom program definition for KodOS.
-- Redis is an in-memory data store used for caching, sessions, and more.
--
-- Copy this file to ~/.kod/plugins/programs/redis.lua to use it in your configuration.

return {
    -- Unique identifier for this program
    name = "redis",
    
    -- Human-readable description
    description = "Redis - In-memory data structure store",
    
    -- Configuration schema: defines all available options
    schema = {
        -- Enable/disable flag
        enable = {
            type = "boolean",
            default = false,
            description = "Enable Redis server"
        },
        
        -- Version selection
        version = {
            type = "string",
            default = "latest",
            description = "Redis version (e.g., '7.0', 'latest')"
        },
        
        -- Server port
        port = {
            type = "number",
            default = 6379,
            description = "Redis server port"
        },
        
        -- Bind address
        bind_address = {
            type = "string",
            default = "127.0.0.1",
            description = "IP address to bind to (127.0.0.1 for localhost only, 0.0.0.0 for all interfaces)"
        },
        
        -- Data persistence
        persistence = {
            type = "table",
            default = {},
            description = "Data persistence options"
        },
        
        -- Maximum memory
        max_memory = {
            type = "string",
            default = "256mb",
            description = "Maximum memory Redis can use (e.g., '256mb', '1gb')"
        },
        
        -- Eviction policy
        eviction_policy = {
            type = "string",
            default = "allkeys-lru",
            description = "Eviction policy when max memory is reached"
        },
        
        -- Additional packages
        extra_packages = {
            type = "array",
            default = {},
            description = "Additional packages to install (e.g., redis-cli, redis-modules)"
        },
    },
    
    -- Installation function
    -- Called with validated configuration and execution function
    install = function(config, exec_fn)
        -- Skip if not enabled
        if not config.enable then
            return
        end
        
        -- Determine package name based on version
        local package_name = "redis"
        if config.version and config.version ~= "latest" then
            package_name = "redis-" .. config.version
        end
        
        -- Install Redis package
        exec_fn("pacman -S --noconfirm " .. package_name)
        
        -- Install any extra packages
        if config.extra_packages and #config.extra_packages > 0 then
            for _, pkg in ipairs(config.extra_packages) do
                exec_fn("pacman -S --noconfirm " .. pkg)
            end
        end
        
        -- Create Redis configuration file
        local redis_conf = "/etc/redis/redis.conf"
        local conf_content = 
            "# Generated by KodOS\n" ..
            "port " .. config.port .. "\n" ..
            "bind " .. config.bind_address .. "\n" ..
            "maxmemory " .. config.max_memory .. "\n" ..
            "maxmemory-policy " .. config.eviction_policy .. "\n" ..
            "dir /var/lib/redis\n" ..
            "logfile /var/log/redis/redis.log\n"
        
        -- Add persistence settings if configured
        if config.persistence.enabled then
            conf_content = conf_content ..
                "save 900 1\n" ..
                "save 300 10\n" ..
                "save 60 10000\n" ..
                "appendonly yes\n" ..
                "appendfilename \"appendonly.aof\"\n"
        else
            conf_content = conf_content .. "save \"\"\n"
        end
        
        -- Write configuration using shell heredoc
        exec_fn("mkdir -p /var/lib/redis /var/log/redis")
        exec_fn("chown redis:redis /var/lib/redis /var/log/redis")
        exec_fn("chmod 755 /var/lib/redis /var/log/redis")
        
        -- Create a temporary config file and move it
        exec_fn("cat > /tmp/redis.conf << 'EOF'\n" .. conf_content .. "EOF\n")
        exec_fn("mv /tmp/redis.conf " .. redis_conf)
        exec_fn("chown redis:redis " .. redis_conf)
        exec_fn("chmod 640 " .. redis_conf)
        
        -- Enable and start the service
        exec_fn("systemctl enable redis")
        exec_fn("systemctl restart redis")
        
        -- Verify installation
        exec_fn("systemctl status redis")
    end,
    
    -- Validation function
    -- Returns (success: boolean, error: string?)
    validate = function(config)
        -- Only validate if enabled
        if not config.enable then
            return true
        end
        
        -- Validate port number
        if config.port then
            if type(config.port) ~= "number" then
                return false, "port must be a number"
            end
            if config.port < 1 or config.port > 65535 then
                return false, "port must be between 1 and 65535"
            end
        end
        
        -- Validate bind address
        if config.bind_address then
            if not config.bind_address:match("^[%d%.]+$") and 
               config.bind_address ~= "0.0.0.0" and
               config.bind_address ~= "127.0.0.1" and
               config.bind_address ~= "localhost" then
                return false, "bind_address must be a valid IP address"
            end
        end
        
        -- Validate max memory format
        if config.max_memory then
            if not config.max_memory:match("^%d+[kmg]?b?$") then
                return false, "max_memory must be in format like '256mb', '1gb'"
            end
        end
        
        -- Validate eviction policy
        local valid_policies = {
            ["noeviction"] = true,
            ["allkeys-lru"] = true,
            ["allkeys-lfu"] = true,
            ["volatile-lru"] = true,
            ["volatile-lfu"] = true,
            ["volatile-ttl"] = true,
            ["volatile-random"] = true,
            ["allkeys-random"] = true,
        }
        
        if config.eviction_policy and not valid_policies[config.eviction_policy] then
            return false, "invalid eviction_policy: " .. config.eviction_policy
        end
        
        -- Validate version format
        if config.version and config.version ~= "latest" then
            if not config.version:match("^%d+%.%d+") then
                return false, "version must be in format like '7.0', 'latest'"
            end
        end
        
        -- Validate extra_packages is an array
        if config.extra_packages then
            if type(config.extra_packages) ~= "table" then
                return false, "extra_packages must be an array"
            end
        end
        
        return true
    end,
}

-- ============================================================================
-- Usage Example in KodOS Configuration
-- ============================================================================
--
-- In your ~/.kod/configuration.lua or similar:
--
-- return {
--     users = {
--         myuser = {
--             programs = {
--                 redis = {
--                     enable = true,
--                     version = "latest",
--                     port = 6379,
--                     bind_address = "127.0.0.1",
--                     max_memory = "256mb",
--                     eviction_policy = "allkeys-lru",
--                     persistence = {
--                         enabled = true
--                     },
--                     extra_packages = {
--                         "redis-cli",
--                     }
--                 }
--             }
--         }
--     }
-- }
--
-- Command to verify: redis-cli ping
-- Should return: PONG
--
-- ============================================================================
