#!/bin/bash

OVERLAY_ROOT="/kod/overlay/$USER"

if [ ! -d /kod/overlay ]; then
    mkdir -p /kod/overlay
fi
mkdir -p $OVERLAY_ROOT
mkdir -p $OVERLAY_ROOT/{upper,work,rootfs}

sudo mount -t overlay overlay -o lowerdir=/,upperdir=${OVERLAY_ROOT}/upper,workdir=${OVERLAY_ROOT}/work ${OVERLAY_ROOT}/rootfs

if [ "$1" == "-p" ]; then 
    sudo mount --bind /var/cache ${OVERLAY_ROOT}/rootfs/var/cache
    sudo mount --bind /var/tmp ${OVERLAY_ROOT}/rootfs/var/tmp
    sudo mount --bind /var/log ${OVERLAY_ROOT}/rootfs/var/log

    sudo arch-chroot ${OVERLAY_ROOT}/rootfs pacman -S --noconfirm $2
fi

proot -R ${OVERLAY_ROOT}/rootfs -b /var/cache -b /var/tmp -b /var/log /bin/bash

sudo umount -R ${OVERLAY_ROOT}/rootfs

sudo rm -rf ${OVERLAY_ROOT}
